### ISSUE TITLE
Map and String class issues

### ISSUE THREAD

**Issue by ciarrapeters** [az0977776/cs4500-a1p2-design#11]
Map class:
- Why is the destructor and the put method virtual? Shouldn't methods only be virtual if something will be subclassing from it?
- Could you please put a hash_me_() method in your Map class? If you want us to use it for hashes, we need the spec there.
- Did you intend to have a to_string() method in your Map class? It is virtual in Object, and Map implements Object, meaning Map should have a to_string(). Also, why is it in Object? Could you just make separate methods in Map for to_string if it is not necessary in Object?

String class:
- Could you please explain the third constructor String(bool steal, char* s). We don't quite understand what its purpose is.
- Can you also add a hash_me_() in your Object class and make it virtual, and add hash_me_() in your String class? We need this in order to be able to implement hash() and hash_me_() like you asked us to in your comments.

Thank you!

**Comment by az0977776** [comment]
Hi, next time can you create one issue per problem:

> Briefly, if you think the tests or spec are broken or mistaken, file issues or pull requests with the designers (one issue/pull request per flaw, as is the standard practice.)

* we removed the virtual and assuming that our map will not be inherited from.
* we changed the api specs from jan vitek's version to chase bishop's version here: https://github.com/chasebish/cwc_object_string so we will no longer need that function
* function has been removed as above

* it's original purpose was to take ownership of the char* s, but this function has been removed
* this has also been removed

**Comment by ciarrapeters** [comment]
Thank you very much!!!
