### ISSUE TITLE
Map(keys, values) Constructor

### ISSUE THREAD

**Issue by ciarrapeters** [az0977776/cs4500-a1p2-design#18]
Could you make another constructor that takes keys and values? We think it would be really useful for your clone() method. Since "this" is not a keyword in C, it is difficult for us to pass in a Map to the copy constructor which takes in a Map.

Thank you!

**Comment by az0977776** [comment]
What format do you think the key and values should be passed in as? There are other ways to create a clone of a map using the other functions in Map.

**Comment by ashnashah123** [comment]
Never mind, we figured it out and forgot to close this
