### ISSUE TITLE
Clarify purpose statement of get_keys()

### ISSUE THREAD

**Issue by ciarrapeters** [az0977776/cs4500-a1p2-design#19]
Could you please clarify the purpose statement of get_keys()?:
```
// returns an array of copied keys in map, not sorted
// call size to determine the number String*
```
We do not understand what the second line has to do with this method; we thought this method should just return the keys.

**Comment by az0977776** [comment]
To get the length of the Object* list you can call size() on the map, because the number of keys is the same as the number of key-value pairs
