### ISSUE TITLE
Overwrite puts

### ISSUE THREAD

**Issue by angelawang24** [az0977776/cs4500-a1p2-design#22]
If a key already exists in the map, should the value be overwritten? Your specs and tests don't reflect either choice

**Comment by az0977776** [comment]
It should overwrite as conventional maps do.

Test is here: https://github.com/az0977776/cs4500-a1p2-design/blob/master/test-map.cpp#L157

**Comment by melina7890** [comment]
The tests exist, but could be modified to show that put overwrites by calling the get function with the same key

**Comment by az0977776** [comment]
tests added
