### ISSUE TITLE
Error in test updates

### ISSUE THREAD

**Issue by ciarrapeters** [az0977776/cs4500-a1p2-design#24]
In your test_hash(), on line 202, did you mean to use "m1"? We assumed you did, because the test is testing that both m0 and m1 are equal, but they are not if you add to m0 like line 202 is doing.
![image](https://user-images.githubusercontent.com/17356801/73493473-d2d0de00-4380-11ea-82c6-bdbcbc0caf61.png)

In addition, you don't call test_hash() in your main. Could you please address these issues? Thank you

**Comment by az0977776** [comment]
thanks
