### ISSUE TITLE
size method return type size_t

### ISSUE THREAD

**Issue by angelawang24** [az0977776/cs4500-a1p2-design#25]
Can you change your size method to return a size_t instead of an int? Thanks

**Comment by ciarrapeters** [comment]
Do you mind telling us why this is better? We have an implementation that works with int, and we would prefer not changing it to size_t.
Thanks 😅

**Comment by frankkulak** [comment]
@ciarrapeters, I agree with @angelawang24 - please change it to a `size_t`. Pretty much everyone else's implementation uses a `size_t` rather than `int` for every size/length, and it's better to maintain that consistency rather than mixes types (`size_t` can be much bigger than `int`).

**Comment by ciarrapeters** [comment]
Okay! That makes sense. Thanks for the heads up.

**Comment by az0977776** [comment]
updated to size_t, consistency
