### ISSUE TITLE
String and Object Classes

### ISSUE THREAD

**Issue by angelawang24** [az0977776/cs4500-a1p2-design#3]
Could you add all the methods/headers for the string and object class for consistency between all project? It can all be found on this piazza post: https://piazza.com/class/k51bluky59n2jr?cid=166

**Comment by spar36** [comment]
I agree. We need to get everyone to agree and it will make it easier for everyone if we all have the same specs for those type.

**Comment by spar36** [comment]
also https://piazza.com/class/k51bluky59n2jr?cid=330

**Comment by az0977776** [comment]
will update +1

**Comment by barthch** [comment]
Done
PR #6
