### ISSUE TITLE
MapNode

### ISSUE THREAD

**Issue by angelawang24** [az0977776/cs4500-a1p2-design#4]
Could you add another class that represents one entry in the map? Like a MapNode that has an Object* key and value, with methods get_key(), get_value(), equals(Object* o), and hash()

**Comment by az0977776** [comment]
no, if that is the way you want to implement your map, you can create that class and include that functionality on your end.

**Comment by elehman16** [comment]
Per the Piazza: "You have to negotiate with the spec team, which classes to add, or which method signatures to change." Just letting you know that you are not allowed to create new classes without the owners permission!

**Comment by az0977776** [comment]
im assuming this is coming from https://piazza.com/class/k51bluky59n2jr?cid=315, but i think we are allowed to create as many "private" classes and methods to help us in our implementation of the public API.
