### ISSUE TITLE
Remove print() from Object class

### ISSUE THREAD

**Issue by frankkulak** [az0977776/cs4500-a1p2-design#8]
The `print()` method in the Object class is unnecessary and difficult to implement when `std::cout` is not available in CwC. Please remove it. 

If you need to print an Object's pointer or `to_string()` somewhere, then just use `std::cout << object->to_string()` rather than including `print()` as a built-in method.

**Comment by Nomenokes** [comment]
You can use printf or puts, it's in the C standard library

**Comment by frankkulak** [comment]
@Nomenokes that's true, but it's still unnecessary. We don't want to add `print()` to our definition of Object because then the people using our code will have to add it to theirs, the people using their code have to add it to theirs, and so on, whereas if you remove it, no one using your code is obligated to make changes.

**Comment by az0977776** [comment]
we are now planning to follow: https://piazza.com/class/k51bluky59n2jr?cid=345
the prints will be removed in #13
